DROP TABLE menu_item IF EXISTS;
DROP TABLE dish IF EXISTS;
DROP TABLE restaurant IF EXISTS;
DROP TABLE users IF EXISTS;

CREATE TABLE restaurant
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE dish
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    price BIGINT      NOT NULL
);

CREATE TABLE menu_item
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    restaurant_id INTEGER NOT NULL,
    date          DATE    NOT NULL,
    dish_id       INTEGER NOT NULL,

    CONSTRAINT menu_item_dish_id_fkey FOREIGN KEY (dish_id)
        REFERENCES dish (id)
        ON DELETE CASCADE,
    CONSTRAINT menu_item_restaurant_id_fkey FOREIGN KEY (restaurant_id)
        REFERENCES restaurant (id)
        ON DELETE CASCADE
);

create index menu_item_restaurant_id_date_index
    on menu_item (restaurant_id, date);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    name       VARCHAR(255)          NOT NULL,
    email      VARCHAR(255)          NOT NULL,
    password   VARCHAR(255)          NOT NULL,
    enabled    BOOLEAN DEFAULT true  NOT NULL,
    registered DATE    DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX user_unique_email_index
    ON users (email);
